package engestofte.domain.event.enums;

public enum EventStatus {
	APPROVED,
	FOLLOW_UP_REQUIRED,
	OWNER_FOLLOW_UP_REQUIRED,
	CLOSED_BY_CUSTOMER,
	CLOSED_BY_OWNER,
	AWAITING_APPROVAL,
	AWAITING_DEPOSIT,
	BOOKED,
	CANCELLED_BY_CUSTOMER
}
