package engestofte.domain.enquiry.enums;

public enum EnquiryStatus {
	SUBMITTED,
	UNDER_REVIEW,
	AWAITING_CUSTOMER,
	FOLLOW_UP_REQUIRED,
	OWNER_FOLLOW_UP_REQUIRED,
	APPROVED,
	CLOSED_BY_OWNER,
	CLOSED_BY_CUSTOMER,
	CANCELLED_BY_CUSTOMER
}
